version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openbrewerydb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "npm run db:push && npm start"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://user:password@db:5432/openbrewerydb?schema=public
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
volumes:
  db_data:
